### ISSUE TITLE
truffle serve error

### ISSUE THREAD

**Issue by CyberNano** [ConsenSys/Token-Factory#38]
After "npm install" I try to run "truffle serve" and get this:

truffle serve
Error: Couldn't find preset "es2015" relative to directory "/home/asphyxia/Downloads/Token-Factory-master"
    at /home/asphyxia/.nvm/versions/node/v7.0.0/lib/node_modules/truffle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19
    at Array.map (native)
    at OptionManager.resolvePresets (/home/asphyxia/.nvm/versions/node/v7.0.0/lib/node_modules/truffle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/home/asphyxia/.nvm/versions/node/v7.0.0/lib/node_modules/truffle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/home/asphyxia/.nvm/versions/node/v7.0.0/lib/node_modules/truffle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/home/asphyxia/.nvm/versions/node/v7.0.0/lib/node_modules/truffle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at compile (/home/asphyxia/.nvm/versions/node/v7.0.0/lib/node_modules/truffle/node_modules/babel-register/lib/node.js:103:45)
    at loader (/home/asphyxia/.nvm/versions/node/v7.0.0/lib/node_modules/truffle/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/home/asphyxia/.nvm/versions/node/v7.0.0/lib/node_modules/truffle/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at module.exports (/home/asphyxia/.nvm/versions/node/v7.0.0/lib/node_modules/truffle/lib/require-nocache.js:5:10)
    at Function.Config.load (/home/asphyxia/.nvm/versions/node/v7.0.0/lib/node_modules/truffle/lib/config.js:196:23)

**Comment by flyswatter** [comment]
My guess is that the package.json is missing a line like this:

https://github.com/flyswatter/react-hyperscript-beefy-es6-boilerplate/blob/master/package.json#L16 <https://github.com/flyswatter/react-hyperscript-beefy-es6-boilerplate/blob/master/package.json#L16>

Also requires a dev-dependency:

https://github.com/flyswatter/react-hyperscript-beefy-es6-boilerplate/blob/master/package.json#L43 <https://github.com/flyswatter/react-hyperscript-beefy-es6-boilerplate/blob/master/package.json#L43>
