### ISSUE TITLE
Error: spawn webpack ENOENT

### ISSUE THREAD

**Issue by thackerronak** [ConsenSys/Token-Factory#48]
showing Error: spawn webpack ENOENT when I run the below command 
truffle serve
Serving static assets in ./build on port 8080...
Rebuilding...
Running `webpack`...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by jetpack3331** [comment]
I have the same error on Windows 10, are u using Windows platform?

**Comment by mikenk2010** [comment]
You should run npm install again to make sure cross-env is available.
